### PR TITLE
Add tutorial for new users to armory-example

### PR DESCRIPTION
**Pull request by ng390**
Partially addresses #61

### CODE REVIEW

**Comment by davidslater** [comment]
@mwartell can you review this PR? Since it's a tutorial, I thought that you would be able to provide the best outside prospective from inside the team.

**Review by mwartell — APPROVED** [review]
These comments have been obsoleted by  downstream commits.

**Comment by mwartell** [comment]
LGTM after my commits, but @ng390 might want to get a second reviewer

**Comment by davidslater** [comment]
I won't have time to review it today. You may need to see if someone else on the team has cycles.

**Pull request merged**
